- hosts: local_instance
  become: true
  tasks:
    - name: Updating Java
      yum:
        name: java-1.8.0-openjdk
        state: latest
    - name: Setting Alternatives
      shell : alternatives --config java <<< '2'
    - name: Updating Git
      yum:
        name: git
        state: latest
    - name: download agent.jar file
      get_url:
        url: http://10.40.73.106:8000/jnlpJars/agent.jar
        dest: /tmp/agent.jar
    - name: Adding to Jenking Slave
      shell: nohup java -jar agent.jar -jnlpUrl http://10.40.73.106:8000/computer/appserver/slave-agent.jnlp -secret c5251f77985f70fe09a5e6155cbe0a58d30adb1f5773d3bfd10ff5a1ba72424d -workDir "/home/jenkins/agent" &
